---
creation_rules:
  - # IMPORTANT: This rule MUST be above the others
    path_regex: talos/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1gwrvmezt3hkxrcs0zyza62r5acx7jhpxm5vaq86wg8t6nv97wfdsm5mwsz"
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1gwrvmezt3hkxrcs0zyza62r5acx7jhpxm5vaq86wg8t6nv97wfdsm5mwsz"
